apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  mongodb_uri: bW9uZ29kYjovL21vbmdvOm1vbmdvMTIzQGRldm9wc2xlYWRlcnNpbC10ZXN0LmNsdXN0ZXItY2t0Z3IxZGN6NGN6LnVzLWVhc3QtMi5kb2NkYi5hbWF6b25hd3MuY29tOjI3MDE3Lz9yZXBsaWNhU2V0PXJzMCZyZWFkUHJlZmVyZW5jZT1zZWNvbmRhcnlQcmVmZXJyZWQmcmV0cnlXcml0ZXM9ZmFsc2U=
