apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer  # Regular k8s Service manifest with type as LoadBalancer
  selector:
    app: {{ .Release.Name }} 
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.targetPort }}